_cargo: site-functions/_cargo
_rustup: site-functions/_rustup
_stack: site-functions/_stack
_tmuxinator: site-functions/_tmuxinator
astylerc: .astylerc
beamer_template_tex: .pandoc/templates/beamer_template.tex
ctags: .ctags
dups: bin/dups
genos_hsfiles: .stack/templates/genos.hsfiles
ghci: .ghci
gitconfig: .gitconfig
gvimrc: .gvimrc
haskeline: .haskeline
imgcat: bin/imgcat
inputrc: .inputrc
md2beamer: bin/md2beamer
md2tufte: bin/md2tufte
nvim: .config/nvim
passive: bin/passive
profiles_clj: .lein/profiles.clj
pylintrc: .pylintrc
sbclrc: .sbclrc
scalariform_properties: .scalariform.properties
stack_config: .stack/config.yaml
stack_global: .stack/global-project/stack.yaml
start_your_day: bin/start_your_day
stylish_haskell: .stylish-haskell.yaml
tmux_conf: .tmux.conf
tufte_template_tex: .pandoc/templates/tufte_template.tex
vim: .vim
vimrc: .vimrc
weasel: bin/weasel
zshenv: .zshenv
zshprompt: .zshprompt
zshrc: .zshrc
